# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField()),
                ('author', models.TextField()),
                ('is_finished', models.BooleanField()),
            ],
            options={
                'db_table': 'reads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'runs',
                'managed': True,
            },
        ),
    ]
