# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryan_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='read',
            old_name='book',
            new_name='title',
        ),
    ]
